name: Build and test

on:
  # Run on pushes to master
  push:
    branches:
      - master
  # And all pull requests
  pull_request:


jobs:
  build:
    env:
      ASQ: /home/firedrake/asQ
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The docker container to use.
    container:
      image: firedrakeproject/firedrake-vanilla:latest
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      # FIXME: can't use this checkout stuff until firedrake docker
      # image has USER root
      # - uses: actions/checkout@v2
      - name: Checkout
        run: |
          mkdir -p $ASQ
          cd $ASQ
          git clone --depth 1 https://github.com/$GITHUB_REPOSITORY.git .
          git fetch origin $GITHUB_SHA:temporary-ci-branch
          git checkout $GITHUB_SHA || (git fetch && git checkout $GITHUB_SHA)
      - name: Install
        run: |
          . /home/firedrake/firedrake/bin/activate
          cd $ASQ
          python -m pip install -e .
      # Uncomment this to run flake8, currently billions of errors.
      - name: Lint
        continue-on-error: true
        run: |
          . /home/firedrake/firedrake/bin/activate
          flake8 .
      - name: Test
        run: |
          # Work around docker image user not being root
          export HOME=/home/firedrake
          . /home/firedrake/firedrake/bin/activate
          cd $ASQ
          pytest -v test