name: Build and test

on:
  # Run on pushes to master
  push:
    branches:
      - master
  # And all pull requests
  pull_request:

concurrency:
  # Cancels jobs running if new commits are pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build and test asQ"
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    # The docker container to use.
    container:
      image: firedrakeproject/firedrake-vanilla:latest
    env:
      ASQ_CI_TESTS: 1
      OMP_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      - name: Fix permissions
        # Firedrake's Dockerfile sets USER to firedrake instead of
        # using the default user, so we need to update file
        # permissions for this image to work on GH Actions.
        # See https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem
        # (copied from https://help.github.com/en/actions/migrating-to-github-actions/migrating-from-circleci-to-github-actions)
        run: |
          sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2
      - name: Install test dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install pytest-timeout
          python -m pip install pytest-cov
          python -m pip uninstall --yes pytest-mpi
      - name: Install
        run: |
          . /home/firedrake/firedrake/bin/activate
          firedrake-status
          FFTW_INCLUDE_DIR=/home/firedrake/firedrake/src/petsc/default/include FFTW_LIBRARY_DIR=/home/firedrake/firedrake/src/petsc/default/lib python -m pip install mpi4py-fft 
          python -m pip install --upgrade scipy
          python -m pip install -e .
      - name: Lint
        run: |
          . /home/firedrake/firedrake/bin/activate
          flake8 .
      - name: Test
        run: |
          . /home/firedrake/firedrake/bin/activate
          python --version
          python -m pytest --version
          python -m pytest -vvv -s -n 4 --durations=0 --timeout=600 --cov=asQ tests/
