name: Build and test
on:
  # Run on pushes
  push:
  # And all pull requests
  pull_request:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The docker container to use.
    container: firedrakeproject/firedrake:latest
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install -e .
      - name: Lint
        run: |
          . /home/firedrake/firedrake/bin/activate
          flake8 .
      - name: Test
        run: |
          . /home/firedrake/firedrake/bin/activate
          pytest test